Repository MSHS-OAO/Balanced-Scorecards, pull requests merged in 2024-10, with the labels that each got.

#243 Update biomed
  Functions/Processing/biomed.R
  server.R
  ui.R
Labels: Biomed

#240 Update periop processing for new file
  Functions/Processing/peri_op_processing.R
Labels: Update, PeriOp

#245 Update rounding
  Functions/Processing/peri_op_processing.R
Labels: Update, PeriOp

#247 Updated processing function and write and merge messages
  Functions/Processing/patient_experience.R
  Functions/pt_exp_server_function.R
  Functions/write_table_and_merge_pt_exp.R
Labels: PatientExperience/PressGaney

#242 Re organized code for LAB KPI metrics
  Archive/lab_processing.R
  Functions/Processing/lab_processing.R
  SQLQueries/BSC_LAB_KPI.sql
  SQLQueries/ModifiedMetricsFinalDF.sql
  server.R
  ui.R
Labels: enhancement, LabKPI

#248 Got the lab proficiecy back
  server.R
Labels: LabKPI

#244 Updated Patient Transport
  Functions/Processing/patient_transport_function.R
  Functions/write_table_and_merge.R
Labels: Patient Transport
